[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/chat/*"
  to = "https://chat.ecnu.edu.cn/open/api/v1/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/coze/*"
  to = "https://api.coze.cn/:splat"
  status = 200
  force = true
